### ISSUE TITLE
feature: Upgrade Android.Support to AndroidX

### ISSUE THREAD

**Issue by KevinvdBurg** [reactiveui/ReactiveUI.Validation#129]
Currently ReactiveUI.Validation only support the Android.Support Library most ReactiveUI Packages are updated to use AndroidX

It would be great if ReactiveUI.Validation supports AndroidX

**Comment by worldbeater** [comment]
Currently, we have [ReactiveUI.AndroidSupport](https://www.nuget.org/packages/ReactiveUI.AndroidSupport/) and [ReactiveUI.AndroidX](https://www.nuget.org/packages/ReactiveUI.AndroidX/) packages available on NuGet. Curious if we should do the same to `ReactiveUI.Validation`, and e.g. publish the library for `MonoAndroid` exposing the platform-independent APIs, and then publish Android-specific extensions as `ReactiveUI.Validation.AndroidSupport` and `ReactiveUI.Validation.AndroidX`.

Or, should we just replace the dependency on `Xamarin.Android.Support.Design` with a newer `AndroidX` dependency when ship a newer library version? This way we immediately drop the support for `Android.Support`. https://github.com/reactiveui/ReactiveUI.Validation/blob/main/src/ReactiveUI.Validation/ReactiveUI.Validation.csproj#L18

Probably the former option is better than the latter. However, both options will introduce a breaking change.

**Comment by glennawatson** [comment]
Yeah. The former will provide maximum parity with the main reactiveui project.
