### ISSUE TITLE
feature: Make `ValidationText` immutable, and add `Empty` property.

### ISSUE THREAD

**Issue by thargy** [reactiveui/ReactiveUI.Validation#141]
**Describe the solution you'd like**
Currently `ValidationText` is mutable, allowing additional `texts` to be added, or for the collection to be cleared.  This functionality is not currently used in the library and has performance and thread-safety implications.

**Describe alternatives you've considered**
Having an alternative immutable implementation that can be used interchangeably with the existing mutable version, does not remove the thread-safety issues of accessing the collection whilst it may be being mutated.

**Describe suggestions on how to achieve the feature**
The `Add()` and `Clear()` methods should be removed, and the underlying list changed to a nullable array of _texts (`null` for empty).  Although this is a breaking change, it is worth it as it allows a static readonly `ValidationText.Empty` singleton property to be added and reduces memory utilisation.

Ideally, the current constructors should be deprecated for a factory method that returns `Empty` when supplied with an empty enumerable.

**Additional context**

**Comment by worldbeater** [comment]
Should be resolved in https://github.com/reactiveui/ReactiveUI.Validation/pull/144
