### ISSUE TITLE
Make Add and Clear operations immutable.

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI.Validation#146]
## When Add() &amp; Clear() are obsolesced this should be made read-only.

https://github.com/reactiveui/ReactiveUI.Validation/blob/2c54af461a64a4013856b0336d6cccff8ec79f4c/src/ReactiveUI.Validation/Collections/ValidationText.cs#L29-L34

---

###### This comment was generated by [todo](https://todo.jasonet.co) based on a `TODO` comment in 2c54af461a64a4013856b0336d6cccff8ec79f4c in #144. cc @thargy.

_Originally posted by @todo in https://github.com/reactiveui/ReactiveUI.Validation/pull/144#issuecomment-712504502_

**Comment by worldbeater** [comment]
Note: this is planned for ReactiveUI.Validation 2.0 that we are going to ship a few months later. A couple of months should hopefully be enough for our users to update their codebases by removing calls to methods, properties, and classes that are marked as `[Obsolete]`. In ReactiveUI.Validation 2.0, these `[Obsolete]` classes are going to be removed.

**Comment by worldbeater** [comment]
Closed by https://github.com/reactiveui/ReactiveUI.Validation/pull/170
