### ISSUE TITLE
[BUG] ValidationContext is not producing updates.

### ISSUE THREAD

**Issue by BenWhite27** [reactiveui/ReactiveUI.Validation#19]
**Describe the bug**
ValidationContext does produce updates and current values do not reflect correct validation status or update in response to property changes.
Tested in a UWP project.

**Steps To Reproduce**
Create a Simple ViewModel and View with associated Bindings.
Create simple validation rules for the ViewModel
Create subscriptions to various Validation public APIs (ValidationContext.ValidationStatusChange, ValidationHelper.ValidationChange, etc.)
Run project and update text in View Controls
Observe that the behavior isn't as expected.

**Expected behavior**
I'd expect the ValidationContext to produce Observable sequeneces indicating the current status of the ViewModel's validation.

**Environment**

- OS:       Windows 10
- Version   1809+
- Device:   Custom build PC and Surface Pro 4

**Additional context**
I'm seeing updates to ValidationHelper.ValidationChanged in accordance with the associated Validation Rule, but no updates beyond the initial values from ValidationContext.

I've attached a bare bones project I've been using to identify this.
[ReactiveUI.Validation.Sample.Uwp.zip](https://github.com/reactiveui/ReactiveUI.Validation/files/3120482/ReactiveUI.Validation.Sample.Uwp.zip)

**Comment by BenWhite27** [comment]
Some more info.

View Code Behind
``` c#
this.Bind(this.ViewModel, vm => vm.Username, v => v.userTxt.Text)
    .DisposeWith(disposables);
this.Bind(this.ViewModel, vm => vm.Password, v => v.passTxt.Password)
    .DisposeWith(disposables);
this.BindCommand(this.ViewModel, vm => vm.Login, v => v.loginBtn)
    .DisposeWith(disposables);
this.BindValidation(this.ViewModel, v => v.errorsTxt.Text)
    .DisposeWith(disposables);
````

ViewModel
```` c#
public class SampleViewModel : ReactiveObject, ISupportsValidation
{
    private ValidationHelper valHelper1;
    private ValidationHelper valHelper2;

    public SampleViewModel()
    {
        this.Login = ReactiveCommand.Create(() => { Debug.WriteLine("Login Invoked"); }, this.IsValid());
        this.SetupValidations();
    }

    [Reactive] public string Username { get; set; } = "";
    [Reactive] public string Password { get; set; } = "";
    public ReactiveCommand<Unit, Unit> Login { get; }

    public ValidationContext ValidationContext { get; } = new ValidationContext();

    private void SetupValidations()
    {
        this.valHelper1 = this.ValidationRule(vm => vm.Username,
            username => !String.IsNullOrWhiteSpace(username),
            "The username cannot be empty");
        this.valHelper1.ValidationChanged.Subscribe(change =>
        {
            Debug.WriteLine("valHelper1.ValidationChanged");
        });

        this.valHelper2 = this.ValidationRule(vm=>vm.Password,
            password => password?.Length > 6,
            "The password must be longer than 6");
        this.valHelper2.ValidationChanged.Subscribe(change =>
        {
            Debug.WriteLine("valHelper2.ValidationChanged");
        });

        this.ValidationContext.ValidationStatusChange.Subscribe(change =>
        {
            Debug.WriteLine("ValidationContext.ValidationStatusChange");
        });

        this.ValidationContext.Valid.Subscribe(change =>
        {
            Debug.WriteLine("ValidationContext.Valid");
        });

        this.IsValid().Subscribe(valid =>
        {
            Debug.WriteLine("this.IsValid()");
        });
    }
}
````

So whilst running the above and updating text in the ui controls I'll see debug console output like the following.
````
// These are the initial values coming from the observables.
valHelper1.ValidationChanged
valHelper2.ValidationChanged
ValidationContext.ValidationStatusChange
ValidationContext.Valid
this.IsValid()

// These are during the test
valHelper1.ValidationChanged
valHelper2.ValidationChanged
valHelper2.ValidationChanged
valHelper1.ValidationChanged
Login Invoked
````
So whilst the rules are updating just fine the state for the whole object is valid all the time and allows me to execute the command.

**Comment by glennawatson** [comment]
@alexmartinezm Mind having a look at this one?

**Comment by alexmartinezm** [comment]
I will check it out over the weekend. Thank you for reporting this @BenWhite27.

**Comment by BenWhite27** [comment]
Thanks all.  I'll download the source myself tonight when I get home and see if I can pin-point it further, I'm still a rookie with Reactive stuff though 😕

**Comment by worldbeater** [comment]
According to the more complex [original example](https://github.com/jcmm33/ReactiveUI.Validation#example), if you'd like to observe changes in validation helpers, you bind directly to them via code-behind bindings, e.g.
```csharp
this.BindValidation(ViewModel, vm => vm.ValHelper1, v => v.ValHelper1Errors.Text);
```
If you'd like to see all validation errors displayed in one TextBox, then simply get rid off those helpers:
```
// Instead of doing this:
this.valHelper1 = this.ValidationRule(vm => vm.Username,
            username => !String.IsNullOrWhiteSpace(username),
            "The username cannot be empty");

// Do this:
this.ValidationRule(vm => vm.Username,
            username => !String.IsNullOrWhiteSpace(username),
            "The username cannot be empty");
```

**Comment by alexmartinezm** [comment]
Hi there, I'm trying to fix this bug, but I cannot reproduce this on a XF project and I don't have a Windows machine. However, I have a VM but the debug session is a bit slow. I hope to get this fixed this weekend.

**Comment by BenWhite27** [comment]
Thanks @alexmartinezm, I had a look at the code but struggled to get my head around it.  If there's anything I can do let me know.  I could setup a windows VM with Visual Studio and the repro for you to remote desktop into if that helps?

When I was looking at the code I think everything inside BasePropertyValidation was working, but the flow of sequences doesn't seem to get past this observable.
https://github.com/reactiveui/ReactiveUI.Validation/blob/0b28a7e4d3de3909139feadbd467d46eea50ccda/src/ReactiveUI.Validation/Contexts/ValidationContext.cs#L82

**Comment by worldbeater** [comment]
@BenWhite27 for a temporary solution, try passing the `ImmediateScheduler.Instance` to your `ValidationContext` constructor. Instead of doing this:
```cs
new ValidationContext();
```
do this:
```cs
// The ImmediateScheduler will make your sample work.
new ValidationContext(ImmediateScheduler.Instance);
```
Currently, `_validationSource` and `_validations` won't stay synchronized due to the following code blocks:
https://github.com/reactiveui/ReactiveUI.Validation/blob/0b28a7e4d3de3909139feadbd467d46eea50ccda/src/ReactiveUI.Validation/Contexts/ValidationContext.cs#L61 https://github.com/reactiveui/ReactiveUI.Validation/blob/0b28a7e4d3de3909139feadbd467d46eea50ccda/src/ReactiveUI.Validation/Contexts/ValidationContext.cs#L83-L88
This issue takes place here due to DynamicData misuse. Feels like I've broken some stuff while migrating from `ReactiveList<T>` to `SourceList<T>`. The `_validations` collection is empty when `validationChangedObservable` ticks on a scheduler other than `ImmediateScheduler`. Working on a fix now.
