### ISSUE TITLE
[ISSUE] Redesign ISupportsValidation

### ISSUE THREAD

**Issue by MovGP0** [reactiveui/ReactiveUI.Validation#35]
**Describe the issue**
It is currently not easily possible to overwrite the `ValidationContext` class for unit testing. It would be better to make it `sealed` and implement a base interface to allow for inversion of control (IOC) in unit tests. 

Instead of 

```csharp
public interface ISupportsValidation
  {
    /// <summary>Gets get the validation context.</summary>
    ValidationContext ValidationContext { get; }
  }

public class ValidationContext : ReactiveObject, IDisposable, IValidationComponent
{
    // ...
}
```

use 

```csharp
public interface IValidationContext : IDisposable, IValidationComponent
{
     // ....
}

public sealed class ValidationContext : ReactiveObject, IValidationContext
{
    // ...
}

public interface ISupportsValidation
  {
    /// <summary>Gets get the validation context.</summary>
    IValidationContext ValidationContext { get; }
  }
```

**Comment by glennawatson** [comment]
Happy to take a PR for this one if you like.

**Comment by worldbeater** [comment]
Btw why would you ever need to mock a `ValidationContext`? In unit tests, you could pass an instance of an `ImmediateScheduler` to the constructor of the `ValidationContext`, and this would result in immediate scheduling required by unit tests. We are following this pattern in `ReactiveUI.Validation.Tests` now. https://github.com/reactiveui/ReactiveUI.Validation/blob/37505fc7bd74f48f252485f67aedb24ac5e2d00b/src/ReactiveUI.Validation.Tests/ValidationContextTests.cs#L41 Or, you could pass a `TestScheduler` from the `ReactiveUI.Testing` package. Setting up the desired validation context behavior should be quite easy via the `fixture.ValidationRule(x => x.PropertyName)` syntax.
