### ISSUE TITLE
BindValidation throws System.NotSupportedException

### ISSUE THREAD

**Issue by NaolShow** [reactiveui/ReactiveUI.Validation#378]
**Describe the bug**

When calling this.BindValidation on a ReactiveUserControl, it throws the exception:
`System.NotSupportedException : 'Index expressions are only supported with constants.'`

**Steps To Reproduce**

Follow: https://www.reactiveui.net/docs/handbook/user-input-validation/
And at the end, the bindValidation will throw an error.

**Expected behavior**

It should not throw an error and just bind correctly

**Code**

ConnectView:
```csharp
public partial class ConnectView : ReactiveUserControl<ConnectViewModel> {

        public ConnectView() {
            InitializeComponent();

            // Input validation
            this.WhenActivated(disposables => {

                this.BindValidation(ViewModel, viewModel => viewModel.Username, view => view.FindControl<TextBlock>("UsernameError").Text).DisposeWith(disposables);

            });

        }

        private void InitializeComponent() {
            AvaloniaXamlLoader.Load(this);
        }

    }
```

ConnectViewModel:
```csharp
public class ConnectViewModel : ReactiveObject, IValidatableViewModel {

        public ValidationContext ValidationContext { get; } = new ValidationContext();

        [Reactive] public string Username { get; set; } = "";
        [Reactive] public string Password { get; set; } = "";

        public ConnectViewModel() {

            // Username cannot be empty
            this.ValidationRule(viewModel => viewModel.Username, username => !string.IsNullOrEmpty(username), "Username cannot be empty..");

        }

    }
```

And of course I have a TextBlock with the x:Name attribute with a value of "UsernameError".

**Additional context**
I am using Avalonia.
Thanks for your help!

**Comment by glennawatson** [comment]
`this.BindValidation(ViewModel, viewModel => viewModel.Username, view => view.FindControl<TextBlock>("UsernameError").Text).DisposeWith(disposables);`

You can't do complex methods in the expression. You have FindControl. Just point towards a property only.

**Comment by worldbeater** [comment]
E.g. if you modify your `ConnectView` as such: 
```cs
public partial class ConnectView : ReactiveUserControl<ConnectViewModel> {
    public ConnectView() {
        InitializeComponent();
        this.WhenActivated(disposables => {
            // Note the change in the third argument passed to BindValidation.
            this.BindValidation(ViewModel, vm => vm.Username, v => v.UsernameError.Text)
                .DisposeWith(disposables);
        });
    }

   private TextBlock UsernameError => this.FindControl<TextBlock>("UsernameError");

    private void InitializeComponent() {
            AvaloniaXamlLoader.Load(this);
    }
}
```
Your example will work, as this change makes the view expression understandable to `ReactiveUI.Validation`. See https://docs.microsoft.com/ru-ru/dotnet/api/system.linq.expressions.expression?view=net-5.0 and https://www.reactiveui.net/docs/handbook/data-binding/#types-of-bindings for more info regarding expressions and their role in ReactiveUI code-behind bindings.

A general recommendation is to always declare references to Avalonia controls as such:
```cs
private TextBlock UsernameError => this.FindControl<TextBlock>("UsernameError");
```
And the good news is that there's a library called [Avalonia.NameGenerator](https://github.com/AvaloniaUI/Avalonia.NameGenerator) that will generate such references automatically. See [documentation](https://github.com/AvaloniaUI/Avalonia.NameGenerator#getting-started) and [generated code examples](https://github.com/AvaloniaUI/Avalonia.NameGenerator#what-do-the-generated-sources-look-like) for more info.

**Comment by NaolShow** [comment]
Thank you so much guys!

It's working when I just create a property that call the FindControl method.
And yes I've seen that there is Avalonia.NameGenerator package, and I was wanting to use it afterwards (but because it was not working with the FindControl I didn't check with the NameGenerator package).
Wasn't knowing that calling a method right here could break everything.

Thank you again! I close this.
