### ISSUE TITLE
[BUG] readme says to use ValidationRule on ReactiveValidationObject but it doesn't exist

### ISSUE THREAD

**Issue by trampster** [reactiveui/ReactiveUI.Validation#433]
**Describe the bug**
The readme says has tells you that for INotifyDataErrorInfo you can inherit ReactiveValidationObject and call this.ValidationRule to add validation rules.

However ReactiveValidationObject doesn't have a ValidationRule method and so the example does not compile:

It can be seen from https://github.com/reactiveui/ReactiveUI.Validation/blob/main/src/ReactiveUI.Validation/Helpers/ReactiveValidationObject.cs which doesn't have a method called ValidationRule

```
public class SampleViewModel : ReactiveValidationObject
{
    public SampleViewModel()
    {
        // this line from the readme doesn't compile because ValidationRule doesn't exist.
        this.ValidationRule(
            viewModel => viewModel.Name, 
            name => !string.IsNullOrWhiteSpace(name),
            "Name shouldn't be null or white space.");
    }

    private string _name = string.Empty;
    public string Name
    {
        get => _name;
        set => this.RaiseAndSetIfChanged(ref _name, value);
    }
}
```

**Steps To Reproduce**
Us the sample from the readme
-> notice it doesn't compile because it uses a method that doesn't exist.

**Expected behavior**
I should be able to follow the readme and have a working validation example

**Environment**
- OS:  ubuntu 20.04
- Device:   Linux desktiop
- Version:  2.2.1
- UI toolkit: Avalonia

**Comment by glennawatson** [comment]
https://github.com/reactiveui/ReactiveUI.Validation/blob/9146f19e26b7b0595bf0355dd23e1c7d9f7c3663/src/ReactiveUI.Validation/Extensions/ValidatableViewModelExtensions.cs#L35

**Comment by glennawatson** [comment]
It exists as a extension method so make sure you include the correct namespaces

**Comment by trampster** [comment]
Oh, thanks.
The problem with extension methods is that they look like normal methods and are completely undiscoverable, (ctrl . reactoring doesn't find it) So you have to just know that it's an extension method, and you have to just know what namespace it's in.

I think it would be helpful if the example in the readme example included the using statement. This would go a long way to helping with the on boarding experience for new users.

I would also suggest rethinking using extension methods like this as it will trip up a lot of new users.

**Comment by glennawatson** [comment]
Good idea in regards to the readme.

Extension methods are used pretty extensively throughout the entire ReactiveUI suite. Visual Studio 2022 has become a lot better at picking up when you should use an extension method these days.

Reason for the extension method it allows you to provide your own object types to validate against since not everyone will want to use the `ReactiveValidationObject` class.
