### ISSUE TITLE
[Bug]: ReactiveValidationObject doesnt work with latest DynamicData version

### ISSUE THREAD

**Issue by reyntjesr** [reactiveui/ReactiveUI.Validation#679]
### Describe the bug 🐞

I think this bug already happened once: [ReactiveValidationObject doesnt work with latest DynamicData version](https://github.com/reactiveui/ReactiveUI.Validation/issues/500)

When I upgrade the dynamicdata package from 8.4.1 to 9.0.1 I get this bug again with the error message: Exception thrown: 'System.MissingMethodException' in ReactiveUI.Validation.dll

### Step to reproduce

I guess any viewmodel with a ReactiveValidationObject base class from packages ReactiveUI.Validation 4.0.9 and dynamicdata 9.0.1

### Expected behavior

no Exceptions

### IDE

Visual Studio 2022

### Operating system

windows 11

### ReactiveUI Version

ReactiveUI.Validation 4.0.9

**Comment by Nextra** [comment]
Confirmed. Anyone pulling in DynamicData 9 through the latest ReactiveUI Version will hit this crash when using Validation.
