### ISSUE TITLE
ArgumentOutOfRangeException when BindValidation is called

### ISSUE THREAD

**Issue by dotfelixb** [reactiveui/ReactiveUI.Validation#75]
**Describe the bug**
If you call BindValidation inside WhenActivated, it throws an exception on app start for both ios and android

```csharp
this.WhenActivated(d =>
{
    // Exception here
    this.BindValidation(
        ViewModel,
        vm => vm.Password,
        page => page.validationLabel.Text).DisposeWith(d);
 });
```
here validationLabel is a Xamarin.Form Label 

**Error/Exception**
page.validationLabel.Text Binding received an Exception! - System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

**Steps To Reproduce**
Same as the example code in ReadMe

**Environment**
Version:   Xamarin (4.6.0.726) ReactiveUI.XamForms (11.3.8) ReactiveUI.Validation (1.4.13)

**Comment by worldbeater** [comment]
This seems to be due to https://github.com/reactiveui/ReactiveUI.Validation/issues/31, so should be fixed in the `main` branch after https://github.com/reactiveui/ReactiveUI.Validation/commit/a6af6213d3c2ab3f3c20edddac45b3456b678d1b.
