### ISSUE TITLE
Increase code coverage

### ISSUE THREAD

**Issue by worldbeater** [reactiveui/ReactiveUI.Validation#8]
**Is your feature request related to a problem? Please describe.**

Currently, codecov reports the following coverage percentage for ReactiveUI.Validation: 

[![Code Coverage](https://codecov.io/gh/reactiveui/ReactiveUI.Validation/branch/main/graph/badge.svg)](https://codecov.io/gh/reactiveui/ReactiveUI.Validation)

**Describe the solution you'd like**

Let's increase coverage to ensure further pull requests won't break existing API etc. 

Probably ~40-50% will be fine enough, but higher coverage is better.

**Describe suggestions on how to achieve the feature**

Let's write more tests!

**Comment by alexmartinezm** [comment]
Totally agree!

**Comment by worldbeater** [comment]
Now we have more than 50% of lines covered, so closing this issue for now. Worth reopening if a regression occurs. In fact, the percentage of the covered lines is even higher, we just aren't testing the autogenerated stuff that isn't used anywhere now https://github.com/reactiveui/ReactiveUI.Validation/tree/main/src/ReactiveUI.Validation/TemplateGenerators and also the `ResolveFor` overloads that aren't used anywhere as well https://github.com/reactiveui/ReactiveUI.Validation/blob/main/src/ReactiveUI.Validation/Extensions/ValidationContextExtensions.cs (not sure what to do with that code)
